### ISSUE TITLE
{1..3,7..9} is expanded to '1..3', '7..9'

### ISSUE THREAD

**Issue by kt97679** [trendels/braceexpand#1]
It will be really nice if we will be able to have compound expressions in braces. For {1..3,7..9} I expect expansion to be 1, 2, 3, 7, 8, 9. This is not bash compatible behavior, but other libraries like https://bitbucket.org/winebarrel/bracecomp/src do this.

**Comment by trendels** [comment]
Hi,
interesting idea, however the focus of this module is to provide Bash-like brace expansion. From that standpoint this behaviour would be unexpected.

**Comment by kt97679** [comment]
Do you think this can be implemented as optional behavior?

**Comment by nils-werner** [comment]
No need to change anything. The correct syntax for both Bash and braceexpand would be

    {{1..3},{7..9}}

**Comment by kt97679** [comment]
Thanks for pointing this out @nils-werner :)!
